### ISSUE TITLE
chez-a-sync licensing language is confusing

### ISSUE THREAD

**Issue by sidkshatriya** [ChrisVine/chez-a-sync#1]
This is an interesting project. Thanks for putting it out there!

I found the licensing information in COPYING a bit confusing to understand

```
chez-a-sync is (like chez scheme 9.4) released under the Apache 2.0
license, as set out below.  (Much of the code is similar to code
released in the guile-a-sync library which is covered by the LGPL v3,
and to that extent it is dual-licensed by me, Chris Vine, the author.)
The pattern matcher in the a-sync/helper/match.ss file has been
released by its authors under the MIT license as set out therein.

Chris Vine, 2016
```

Dual licensing can sometimes be confusing and I'd like to understand what your intention is here. Do you want the project to be licensed under the terms of Apache 2.0 _AND_ LGPL3? Or is your intention to allow the end users who use this project to be able to choose between the licenses i.e. choose either Apache 2.0 _OR_ LGPL3? Or is there another interpretation?

Is there is a reason why chez-a-sync cannot be just plain Apache 2.0 (without the reference to LGPL3 dual licensing language in the COPYING file) ?

As a disclaimer, I am NOT a lawyer. My intention is merely to clarify the license terms of this project from the author. It would be awesome to have simpler licensing for this open source project!

Thanks for putting this up on github!

**Comment by ChrisVine** [comment]
Hi,

It means, or is intended to mean, that the user can use, copy and/or
modify chez-a-sync under the terms of either the Apache License or the
LGPL3, at their choice.  I can clarify this if need be but I thought
that was the generally understood meaning of "dual license".

There is no particular reason why the library could not be released
under the Apache license only, except that I don't know if Apache is
LGPL3 compatible in all respects (it might be, I don't know). If not,
dual licensing gives greater choice to any other open source project
which might want to use chez-a-sync.

Chris

------------------------------------

**Comment by sidkshatriya** [comment]
GPL3 is compatible with Apache 2.0 (but GPL2 is not compatible with Apache 2.0). See https://www.gnu.org/licenses/license-list.en.html#apache2 . I am not sure about LGPL3 and Apache 2.0.

I think clarification of the dual licensing provision would be useful along the lines you suggested. Being explicit about what you mean about "dual" I think would be useful. There are quite a few dual licensed project around the internet and you can always use the language they have used if you'd like.

I still think it would simpler to cover this under a single simple license if that can be possible/feasible/useful.

**Comment by ChrisVine** [comment]
Dual licensing omitted.
